# Site settings
title: André Yoshiaki Kashiwabara
description: > # this means to ignore newlines until "baseurl:"
     André é professor na UTFPR Cornélio Procópio.  Atua com Bioinformática e Biologia Computacional. 
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username:  ayoshiaki
github_username:  ayoshiaki
url:  http://lattes.cnpq.br/3194328548975437
highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false

# Build settings
markdown: kramdown

